-- CREATE TABLE FOR PROJECTS
REATE TABLE IF NOT EXISTS projects (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK (name <> ''),
    priority INTEGER NOT NULL,
    description TEXT,
    deliverydate DATE NOT NULL
);

-- CREATE TABLE FOR TASKS
CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectid INTEGER REFERENCES projects(id)
);

-- INSERT PROJECTS DATA
INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('Make a Web App', 1, 'Using Javascript', '2019-05-12');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('Make a Web App', 1, 'Using Node.js', '2019-05-13');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('Make a Mobile App', 1, 'Using React Native', '2019-05-14');


-- INSERT TASKS DATA
INSERT INTO tasks(name, done, projectid)
    VALUES ('Download Dependencies', false, 1);

INSERT INTO tasks(name, done, projectid)
    VALUES ('Create UI', false, 1);

INSERT INTO tasks(name, done, projectid)
    VALUES ('Download React Native', false, 2);

INSERT INTO tasks(name, done, projectid)
    VALUES ('Download Expo', false, 2);